name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-lint:
    name: Run tests and linter
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Setup C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: gcc
          version: 11
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck cmake build-essential
          
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DENABLE_CLANG_TIDY=ON -DCMAKE_BUILD_TYPE=Debug
          
      - name: Build project
        run: |
          cd build
          make -j4
          
      - name: Run clang-tidy
        run: |
          cd build
          # Запускаем линтер через CMake
          make | grep -i "warning\|error" || true
          
      - name: Run cppcheck
        run: |
          find src -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs cppcheck --enable=all --inconclusive --std=c++17 --error-exitcode=1
          
      - name: Run tests (if exist)
        id: run-tests
        run: |
          if [ -d "test" ] || [ -f "CMakeLists.txt" ]; then
            cd build
            if make help | grep -q "test"; then
              make test
            elif [ -f "CTestTestfile.cmake" ]; then
              ctest --verbose
            else
              echo "No tests found"
            fi
          else
            echo "No test directory found"
          fi
          
      - name: Run specific test executables
        if: always()
        run: |
          if [ -d "build" ]; then
            cd build
            find . -name "*test*" -type f -executable -exec {} \; || true
            find . -name "*Test*" -type f -executable -exec {} \; || true
          fi