name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck
          
      - name: Run clang-tidy on all files
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.cc" -o -name "*.cxx" | \
          xargs -I {} clang-tidy {} -- -std=c++17 -I. || true
          
      - name: Run cppcheck on all files
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 -I. . || true